### PR TITLE
feat: Add and refine Tailwind CSS configuration with improved theme, …

### PR DESCRIPTION
**Pull request by vishalnadarge**
This commit introduces enhancements to the Tailwind CSS configuration file. Key changes include:

- **Content Path Update**: Adjusted the content path to include all HTML templates located in the `./app/templates/` directory to ensure Tailwind CSS purges unused styles correctly.
- **Dark Mode**: Enabled dark mode support by configuring it to toggle based on the `class` strategy.
- **Responsive Design**: Defined custom breakpoints for small, medium, large, extra-large, and 2x extra-large screen sizes, improving the responsiveness of the application.
- **Extended Theme Customization**: Added custom text colors, background colors, and box shadows to enrich the design aesthetics.
- **Animation Enhancements**: Introduced new animations for sparkle effects, including keyframes for smooth transitions and effects, enhancing UI interactivity.
- **Improved Readability**: Updated comments throughout the configuration for clarity and easier maintenance in the future.

These updates aim to enhance the overall user experience and aesthetic of the application.

### CODE REVIEW

**Comment by kom-senapati** [comment]
No issue linked and no template is filled ?

**Comment by vishalnadarge** [comment]
> No issue linked and no template is filled ?

As a beginner I don't found any issue but I have tried to codes

**Comment by kom-senapati** [comment]
You could have raised that issue or asked in community

**Comment by kom-senapati** [comment]
It seems like there's too much work in one pull request, and I'm unsure if new issues have arisen from this PR, so I am closing it.

**Comment by vishalnadarge** [comment]
> It seems like there's too much work in one pull request, and I'm unsure if new issues have arisen from this PR, so I am closing it.

ok i will try with new

**Pull request closed without merging**
