### PR TITLE
FIX Implement GitHub PR Issue Checker Workflow

### LINKED ISSUE #121: Implement PR Issue Checker Workflow
**Description:** We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

**PR Description Check:** Every PR must have a description. If the description is missing, the PR should fail the check.
    
**Issue Reference Check:** The PR description must include an issue reference in the format Fixes #<issue-number>. If the PR is not addressing an existing issue, it should mention Fixes #NEW as a placeholder.

**Acceptance Criteria:**

- A GitHub Action workflow is triggered on PR events (opened, edited).

**The workflow checks the PR body for:**
- A non-empty description.
- The presence of Fixes #<issue-number> or Fixes #NEW.

**If the criteria are not met:**

- The workflow should fail and return clear error messages.

**If the checks pass:**
- A confirmation message is outputted.

**Expected Output:**

- Error message if the PR description is missing.
- Error message if the issue reference is missing or incorrectly formatted.
- Success message when all checks are satisfied.

**Additional Notes:**

- This issue may serve as a foundation for more advanced PR validation (e.g., commit message format, label enforcement).
- We can later extend this to check for specific branch naming conventions or enforce the addition of specific labels.

_**Note**_: i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!

@kom-senapati

### PR DESCRIPTION
**Pull request by smog-root**
Fixes #121 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes #<issue-number>` or `Fixes #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

### CODE REVIEW

**Comment by kom-senapati** [comment]
@smog-root it's giving some error see. Also, do that in Python, not bash. Additionally check if the title starts with FIX, FEAT, DOC, or OTHER.

**Comment by smog-root** [comment]
@kom-senapati you haven't merged it yet. So that's the reason it's giving error!!

I have created same issue to other projects. They haven't faced any errors!!!

Merge it and see!

If it still gives error I will take a look!

**Comment by kom-senapati** [comment]
> @kom-senapati you haven't merged it yet. So that's the reason it's giving error!!
> 
> I have created same issue to other projects. They haven't faced any errors!!!
> 
> Merge it and see!
> 
> If it still gives error. I will take a look!

Error for your PR bro, edit your PR body according to rules lemme see that

**Comment by smog-root** [comment]
I have done it in python too. Merge what ever you like!! 

Don't forget to add labels!

**Comment by smog-root** [comment]
Merge it bro! @kom-senapati

**Comment by smog-root** [comment]
Now it should work!! 😁

**Comment by kom-senapati** [comment]
image
Solve this error first @smog-root

**Comment by smog-root** [comment]
Is it still not working??

**Comment by smog-root** [comment]
IMG_20241018_100450

The error is not in my file!!

**Comment by kom-senapati** [comment]
I think you missed `else` statements here:
image
Do with proper logic

**Comment by kom-senapati** [comment]
LGTM

**Review by MastanSayyad — COMMENTED** [review]
workflow = level 1

**Pull request merged**
