### PR TITLE
Create dark_light.html

### PR DESCRIPTION
**Pull request by sv410**
#91 did a dark and light toggle

### CODE REVIEW

**Comment by kom-senapati** [comment]
Add title and pr desc

**Comment by sv410** [comment]
@kom-senapati pls add level 2

**Comment by kom-senapati** [comment]
You do PR properly first, I am closing all of the other PRs by you.

**Comment by sv410** [comment]
@kom-senapati im sorry its not the way you need to say! thank you i know how to do PR.

**Pull request closed without merging**
