### PR TITLE
Added Table metrices in readme

### PR DESCRIPTION
**Pull request by neeru24**
I've added the table metrices in readme that will be UPDATED AUTOMATICALLY.
kindly merge it @kom-senapati 
Thank you!
fixes: #118 
image

### CODE REVIEW

**Comment by kom-senapati** [comment]
Hey please remove the table and center the badges, that would be better

**Comment by neeru24** [comment]
okk, let me do so

**Comment by neeru24** [comment]
Is it alright? 
image

**Comment by kom-senapati** [comment]
Yup looks good

**Pull request merged**
