### PR TITLE
fix #10: Authentication error management

### LINKED ISSUE #10: UI: Better Error handling and User Experience
- Show the errors in UI on authentication pages like:
image

### PR DESCRIPTION
**Pull request by priyanshuverma-dev**
This PR fixes: #10 

- Adds error messages on authentication pages (siginup/login).

### CODE REVIEW

**Comment by priyanshuverma-dev** [comment]
@kom-senapati Please Review the PR

**Comment by kom-senapati** [comment]
Send ss of the flash errors then will merge it 😀

**Comment by priyanshuverma-dev** [comment]
Have a look 

image

**Comment by kom-senapati** [comment]
Ok merging this!

**Pull request merged**
