### PR TITLE
Refactor app.py for Improved Configuration and Security

### PR DESCRIPTION
**Pull request by chikatlarakesh**
This pull request refactors the app.py file to enhance the configuration and security of the Flask application. The following changes have been made:

- Updated database URI to use environment variables for better security and flexibility.

- Set the secret key to be retrieved from environment variables, providing a safer default mechanism.

- Organized the import statements for clarity.

- Ensured adherence to best practices in Flask application structure.

- These modifications aim to make the application more maintainable and secure for production environments.

### CODE REVIEW

**Comment by kom-senapati** [comment]
You havent raised an issue for this

**Comment by kom-senapati** [comment]
So you are contributing via GSSOC or on your own

**Comment by chikatlarakesh** [comment]
> You havent raised an issue for this

I'm a bit new to this, cant i direct make the change and raise a pull request instead of raising an issue followed by a pull request.

**Comment by chikatlarakesh** [comment]
> So you are contributing via GSSOC or on your own

i'm contributing via GSSoC

**Comment by kom-senapati** [comment]
> > You havent raised an issue for this
> 
> I'm a bit new to this, cant i directly make the change and raise a pull request instead of raising an issue followed by a pull request.

No first you have to get an issue assigned then start working and raise pr. Now you raise the issue for this and I will assign it and give proper labels as well. After that I will merge this pr

**Comment by chikatlarakesh** [comment]
> > > You havent raised an issue for this
> > 
> > 
> > I'm a bit new to this, cant i directly make the change and raise a pull request instead of raising an issue followed by a pull request.
> 
> No first you have to get an issue assigned then start working and raise pr. Now you raise the issue for this and I will assign it and give proper labels as well. After that I will merge this pr

I have submitted the issue, kindly please check.

**Comment by kom-senapati** [comment]
Closes #15

**Pull request merged**
