### PR TITLE
fix: made the hero text responsive and added the re library

### PR DESCRIPTION
**Pull request by parteekxo**
image
the text is now properly aligned on small screens
Fixed: NameError: name 're' is not defined. Did you forget to import 're'
by adding the re library

### CODE REVIEW

**Comment by kom-senapati** [comment]
Do with tailwind

**Comment by parteekxo** [comment]
> Do with tailwind

okie

**Comment by parteekxo** [comment]
@kom-senapati i have made the changes :)

**Comment by kom-senapati** [comment]
Ok cool

**Comment by kom-senapati** [comment]
Closes #94

**Pull request merged**
