### PR TITLE
Added Dark and Light Mode Toggle with Visual Enhancements 

### PR DESCRIPTION
**Pull request by Varsha-1605**
#24 issue solved!

- [ ] Implement a toggle button for light/dark mode with localStorage support.
- [ ] Update HTML/Talwind CSS for dual-theme support with minimal changes.
- [ ] Add smooth Talwind CSS and custom CSS transitions for color changes.
- [ ] Include background gradients and a sparkle effect for the toggle.
- [ ] Adjust the background grid to light lines in dark mode.
- [ ] Updated Readme.md file

### CODE REVIEW

**Comment by kom-senapati** [comment]
Ensure all pages working fine and send me ss of landing and dashboard

**Comment by Varsha-1605** [comment]
@kom-senapati done!

# Landing page(dark mode):
image


# Landing page(light mode):
image


# Dashboard(dark mode):
image


# Dashboard(light mode):
image

**Comment by kom-senapati** [comment]
Try merging the two navbars for the dashboard, hub, and profile pages.

**Comment by Varsha-1605** [comment]
@kom-senapati I have updated the navbar in all the three sections

**Comment by kom-senapati** [comment]
I am not talking about changing the navbar on these pages. I want to merge you base.html navbars with already existing navbars. Or just add dark mode toggle in landing page (for all user) and settings page (for logged in users for dashboard and other pages).

**Comment by Varsha-1605** [comment]
@kom-senapati you can merge it as well otherwise it won't be counted toward my contribution

**Pull request merged**
