### PR TITLE
updated: project structure

### PR DESCRIPTION
**Pull request by htanmo**
closes issue #64

### CODE REVIEW

**Comment by htanmo** [comment]
@kom-senapati please review it.

**Review by htanmo — COMMENTED** [review]
LGTM

**Comment by htanmo** [comment]
@kom-senapati please review the changes.

**Comment by kom-senapati** [comment]
Showing conflicts. Resolve

**Comment by htanmo** [comment]
@kom-senapati done fixing merge conflicts.

**Comment by kom-senapati** [comment]
Change routes.py

**Comment by kom-senapati** [comment]
Ouch Should have merged this PR :/

**Comment by htanmo** [comment]
I will resolve them again no problem.

**Review by htanmo — COMMENTED** [review]
LGTM @kom-senapati please review it.

**Comment by kom-senapati** [comment]
Ok cool, Thanks for contributing

**Pull request merged**
