### PR TITLE
Added speech recognition and speech synthesis methods with mic option in chatbot page

### LINKED ISSUE #172: 🚀 Feature: Migrate speech recognition and speech synthesis pages
### 🔖 Feature description

- Migrate speech recognition and synth Pages

### 🎤 Why is this feature needed ?

React migration

### ✌️ How do you aim to achieve this?

React files

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
### Related Issue
Closes #172 

---

### Description
- Added speech-to-text for capturing the user's voice.
- Changing the microphone icon to a stop icon, which reverts to the microphone upon clicking and sends the voice input
- Added text to speech for bot response

### How Has This Been Tested?

--- Locally

### Screenshots (if applicable)
Animation8

---

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Code style update
- [ ] Breaking change
- [ ] Documentation update

### CODE REVIEW

**Comment by kom-senapati** [comment]
Could you attach a video for this

**Comment by mehul-m-prajapati** [comment]
@kom-senapati : okay added in description

**Comment by mehul-m-prajapati** [comment]
Animation7

**Comment by kom-senapati** [comment]
LGTM

**Pull request merged**
