### PR TITLE
 add top back to top  button

### PR DESCRIPTION
**Pull request by RishabxBhardwaj**
### Title of the Pull Request
- [ ] Have you renamed the PR Title in a meaningful way?

### Related Issue

Closes: #89 

### Type of change
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist

- [ ] My code follows the code style of this project.
- [ ] I have followed the contribution guidelines
- [ ] I have performed a self-review of my own code.
- [ ] I have ensured my changes don't generate any new warnings or errors.
- [ ] I have updated the documentation (if necessary).
- [ ] I have resolved all merge conflicts.

### CODE REVIEW

**Comment by kom-senapati** [comment]
Share a video for this

**Comment by kom-senapati** [comment]
Hey @RishabxBhardwaj , share me a video for this pr and I will merge this

**Comment by kom-senapati** [comment]
Will you share ?

**Comment by RishabxBhardwaj** [comment]
here is the video = https://drive.google.com/file/d/1czkRFVOIU3smyoOi1FSxrbdJj3dlB8tx/view?usp=drivesdk

**Comment by kom-senapati** [comment]
First setup the project in your local PC then run and contribute. I am not taking this as you have not setup

**Comment by kom-senapati** [comment]
Tell me if you do properly or should I close this

**Comment by RishabxBhardwaj** [comment]
Close them

**Pull request closed without merging**
