### PR TITLE
Added export button to download conversation as csv

### LINKED ISSUE #246: 🚀 Feature: Add export button to download chatbot conversation data in csv/text format
### 🔖 Feature description

- Add export button to download chatbot conversation data in csv/text format

### 🎤 Why is this feature needed ?

Export data for analysis

### ✌️ How do you aim to achieve this?

add download option

### 🔄️ Additional Information

t1

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
### Related Issue
Closes #246 

---

### Description
Added export button to download conversation as csv
---

### How Has This Been Tested?
local
---

### Screenshots (if applicable)

https://github.com/user-attachments/assets/7e67f2b5-757c-47f1-835b-da8c522e8118

---

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Code style update
- [ ] Breaking change
- [ ] Documentation update

### CODE REVIEW

**Comment by kom-senapati** [comment]
Use `export-from-json` npm package or similar for the task
Why your output CSV is different?
I thought it would be like

```
Headers
System, <System Prompt>
User, <User Query>
AI, <AI Response>
...
```

**Comment by mehul-m-prajapati** [comment]
@kom-senapati : I am only fetching prompt from user and response from bot (2 columns in csv)

- okay, let me try export-from-json

**Comment by mehul-m-prajapati** [comment]
@kom-senapati : updated code to use `export-from-json` package.

Also, for csv columns, see the data 
r1

-- I think we only need user query and response fields

**Comment by kom-senapati** [comment]
Oh that's also fine

**Pull request merged**
